<a href="https://colab.research.google.com/github/wlfoj/base-machineLearning/blob/main/rh_out.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importando bibliotecas e carregando tabela

In [125]:
# Para manusear os dados
import numpy as np
import pandas as pd
# Para visualização
import matplotlib.pyplot as plt
# Auxliares 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
# Pipeline
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
# Modelos
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
'''AUXILIO PARA CATEGORIZAR AS COLUNAS
Dataset baixado em ->  https://www.kaggle.com/datasets/whenamancodes/hr-employee-attrition

Education
1 'Below College'
2 'College'
3 'Bachelor'
4 'Master'
5 'Doctor'

EnvironmentSatisfaction
1 'Low'
2 'Medium'
3 'High'
4 'Very High'

JobInvolvement
1 'Low'
2 'Medium'
3 'High'
4 'Very High'

JobSatisfaction
1 'Low'
2 'Medium'
3 'High'
4 'Very High'

PerformanceRating
1 'Low'
2 'Good'
3 'Excellent'
4 'Outstanding'

RelationshipSatisfaction
1 'Low'
2 'Medium'
3 'High'
4 'Very High'

WorkLifeBalance
1 'Bad'
2 'Good'
3 'Better'
4 'Best'
'''

In [19]:
df = pd.read_csv("PATH_TO_CSV")
df = df.drop(columns=['Over18', 'EmployeeNumber', 'EmployeeCount']) # Todos os funcionários tem mais de 18 anos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64 
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64 
 6   Education                 1470 non-null   int64 
 7   EducationField            1470 non-null   object
 8   EnvironmentSatisfaction   1470 non-null   int64 
 9   Gender                    1470 non-null   object
 10  HourlyRate                1470 non-null   int64 
 11  JobInvolvement            1470 non-null   int64 
 12  JobLevel                  1470 non-null   int64 
 13  JobRole                   1470 non-null   object
 14  JobSatisfaction         

In [27]:
df.head(20)

Age Attrition     BusinessTravel  DailyRate              Department  \
0    41       Yes      Travel_Rarely       1102                   Sales   
1    49        No  Travel_Frequently        279  Research & Development   
2    37       Yes      Travel_Rarely       1373  Research & Development   
3    33        No  Travel_Frequently       1392  Research & Development   
4    27        No      Travel_Rarely        591  Research & Development   
5    32        No  Travel_Frequently       1005  Research & Development   
6    59        No      Travel_Rarely       1324  Research & Development   
7    30        No      Travel_Rarely       1358  Research & Development   
8    38        No  Travel_Frequently        216  Research & Development   
9    36        No      Travel_Rarely       1299  Research & Development   
10   35        No      Travel_Rarely        809  Research & Development   
11   29        No      Travel_Rarely        153  Research & Development   
12   31        No      Travel_Rarely        670  Research & Development   
13   34        No      Travel_Rarely       1346  Research & Development   
14   28       Yes      Travel_Rarely        103  Research & Development   
15   29        No      Travel_Rarely       1389  Research & Development   
16   32        No      Travel_Rarely        334  Research & Development   
17   22        No         Non-Travel       1123  Research & Development   
18   53        No      Travel_Rarely       1219                   Sales   
19   38        No      Travel_Rarely        371  Research & Development   

    DistanceFromHome  Education EducationField  EnvironmentSatisfaction  \
0                  1          2  Life Sciences                        2   
1                  8          1  Life Sciences                        3   
2                  2          2          Other                        4   
3                  3          4  Life Sciences                        4   
4                  2          1        Medical                        1   
5                  2          2  Life Sciences                        4   
6                  3          3        Medical                        3   
7                 24          1  Life Sciences                        4   
8                 23          3  Life Sciences                        4   
9                 27          3        Medical                        3   
10                16          3        Medical                        1   
11                15          2  Life Sciences                        4   
12                26          1  Life Sciences                        1   
13                19          2        Medical                        2   
14                24          3  Life Sciences                        3   
15                21          4  Life Sciences                        2   
16                 5          2  Life Sciences                        1   
17                16          2        Medical                        4   
18                 2          4  Life Sciences                        1   
19                 2          3  Life Sciences                        4   

    Gender  ...  RelationshipSatisfaction  StandardHours  StockOptionLevel  \
0   Female  ...                         1             80                 0   
1     Male  ...                         4             80                 1   
2     Male  ...                         2             80                 0   
3   Female  ...                         3             80                 0   
4     Male  ...                         4             80                 1   
5     Male  ...                         3             80                 0   
6   Female  ...                         1             80                 3   
7     Male  ...                         2             80                 1   
8     Male  ...                         2             80                 0   
9     Male  ...                         2             80                

In [12]:
## Analisando as features categóricas
display(df['Attrition'].value_counts())
display(60*'-')
display(df['BusinessTravel'].value_counts())
display(60*'-')
display(df['Department'].value_counts())
display(60*'-')
display(df['EducationField'].value_counts())
display(60*'-')
display(df['Gender'].value_counts())
display(60*'-')
display(df['JobRole'].value_counts())
display(60*'-')
display(df['MaritalStatus'].value_counts())
display(60*'-')
display(df['OverTime'].value_counts())

No     1233
Yes     237
Name: Attrition, dtype: int64

'------------------------------------------------------------'

Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: BusinessTravel, dtype: int64

'------------------------------------------------------------'

Research & Development    961
Sales                     446
Human Resources            63
Name: Department, dtype: int64

'------------------------------------------------------------'

Life Sciences       606
Medical             464
Marketing           159
Technical Degree    132
Other                82
Human Resources      27
Name: EducationField, dtype: int64

'------------------------------------------------------------'

Male      882
Female    588
Name: Gender, dtype: int64

'------------------------------------------------------------'

Sales Executive              326
Research Scientist           292
Laboratory Technician        259
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               52
Name: JobRole, dtype: int64

'------------------------------------------------------------'

Married     673
Single      470
Divorced    327
Name: MaritalStatus, dtype: int64

'------------------------------------------------------------'

No     1054
Yes     416
Name: OverTime, dtype: int64

# Processando as colunas

In [87]:
#separa o traino do teste
df_train, df_test, y_train, y_test = train_test_split(X, Y, test_size=0.35, random_state=42)

In [88]:
# Separando as colunas essenciais
col_ordinal = ['Gender', 'BusinessTravel', 'OverTime']#, 'Attrition']
col_1hot = ['JobRole', 'EducationField', 'MaritalStatus', 'Department']

dfx = df.drop(columns=['Gender', 'BusinessTravel', 'OverTime', 'Attrition', 'JobRole', 'EducationField', 'MaritalStatus', 'Department'])
col_num = list(dfx.columns)

# Estruturando Pipelines
num_pipe = Pipeline([
    ("std_sca", StandardScaler())
])

pipeline = ColumnTransformer([
    ("num", num_pipe, col_num),
    ("ordinal", OrdinalEncoder(), col_ordinal),
    ("1hot", OneHotEncoder(), col_1hot)
])
# A ordem das colunas é 1º todas as col_num depois todas as col_ordinal e por fim a col_1hot

# Tratando os dados
df_prepared = pipeline.fit_transform(df_train)

In [89]:
# Separando os dados
Y = df[['Attrition']] # target
X = df.drop(columns=['Attrition']) # features

# Realizando os testes

## Arvore de Decisão

In [124]:
# Treina a rede
tree = DecisionTreeClassifier(max_depth=3)
tree.fit(df_prepared, y_train)

# Faz os testes
test_prepared = pipeline.fit_transform(df_test)
pred = tree.predict(test_prepared)
# Análise da acurácia nos testes
accuracy = accuracy_score(y_test, pred)*100
print ("A acurácia foi de {:.2f}%.".format(accuracy))

A acurácia foi de 85.83%.


In [97]:
# Analisando nos testes
pred = tree.predict(test_prepared)
print("-- Matriz de confusão para testes --")
print(confusion_matrix(y_test, pred))

# Analisando no treinamento
pred = tree.predict(df_prepared)
print("-- Matriz de confusão para treinamento --")
print(confusion_matrix(y_train, pred))

-- Matriz de confusão para testes --
[[418  24]
 [ 60  13]]
-- Matriz de confusão para treinamento --
[[788   3]
 [100  64]]


## Knn

In [123]:
neigh = KNeighborsClassifier(n_neighbors=7)
neigh.fit(df_prepared, y_train)

pred = neigh.predict(test_prepared)
# Análise da acurácia nos testes
accuracy = accuracy_score(y_test, pred)*100
print ("A acurácia foi de {:.2f}%.".format(accuracy))

A acurácia foi de 86.60%.


/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [121]:
pred = neigh.predict(test_prepared)
print("-- Matriz de confusão para testes --")
print(confusion_matrix(y_test, pred))

pred = neigh.predict(df_prepared)
print("-- Matriz de confusão para treino --")
print(confusion_matrix(y_train, pred))

-- Matriz de confusão para testes --
[[434   8]
 [ 65   8]]
-- Matriz de confusão para treino --
[[781  10]
 [115  49]]


## Random Forest

In [126]:
forest = RandomForestClassifier()
forest.fit(df_prepared, y_train)

pred = forest.predict(test_prepared)
# Análise da acurácia nos testes
accuracy = accuracy_score(y_test, pred)*100
print ("A acurácia foi de {:.2f}%.".format(accuracy))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


A acurácia foi de 86.80%.


In [127]:
pred = forest.predict(test_prepared)
print("-- Matriz de confusão para testes --")
print(confusion_matrix(y_test, pred))

pred = forest.predict(df_prepared)
print("-- Matriz de confusão para treino --")
print(confusion_matrix(y_train, pred))

-- Matriz de confusão para testes --
[[436   6]
 [ 62  11]]
-- Matriz de confusão para treino --
[[791   0]
 [  0 164]]


In [134]:
# Extraindo grau de importância de cada coluna 
columns = col_num + col_ordinal + col_1hot
sorted(zip(forest.feature_importances_, columns), reverse= True)

[(0.0707895547835972, 'MonthlyIncome'),
 (0.06299296434798148, 'Age'),
 (0.056652866610221446, 'TotalWorkingYears'),
 (0.05325049950719668, 'OverTime'),
 (0.049370077151009564, 'DailyRate'),
 (0.04537963917071661, 'MonthlyRate'),
 (0.044008366212606405, 'YearsAtCompany'),
 (0.04269558536693967, 'HourlyRate'),
 (0.04254028115194055, 'DistanceFromHome'),
 (0.036601565690687995, 'NumCompaniesWorked'),
 (0.035216325190214844, 'PercentSalaryHike'),
 (0.03284433267028704, 'YearsWithCurrManager'),
 (0.032186635738126815, 'YearsInCurrentRole'),
 (0.026244969311542774, 'TrainingTimesLastYear'),
 (0.02580762220804451, 'EnvironmentSatisfaction'),
 (0.025500519131276392, 'StockOptionLevel'),
 (0.024952203436371057, 'JobSatisfaction'),
 (0.02412337000033056, 'YearsSinceLastPromotion'),
 (0.02366389848538609, 'JobLevel'),
 (0.0223505967955133, 'JobInvolvement'),
 (0.020729924458236657, 'RelationshipSatisfaction'),
 (0.020051171918550163, 'Education'),
 (0.01820576416253405, 'WorkLifeBalance'),
 (0.0